require 'resty/actions/create'
require 'resty/actions/destroy'
require 'resty/actions/edit'
require 'resty/actions/index'
require 'resty/actions/new'
require 'resty/actions/show'
require 'resty/actions/update'
